import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>PROFILE</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Welcome...🖐</h1>
                <a>
                    <Link href="/profile">Click to see profile</Link>
                </a>
            </main>

            <footer className={styles.footer}>
                All rights reserved @ 2022
            </footer>
        </div>
    );
}
